# Generated by Django 4.2.1 on 2023-07-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_district_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='myapp.district'),
        ),
    ]
